[workspace]
members = [
    "linalg",
    "core",
    "tensorflow",
    "onnx",
    "cli",
    "examples/lstm-proptest-onnx-vs-tf",
    "examples/onnx-test-suite",
    "examples/tf-inceptionv3",
    "examples/tf-mobilenet-v2",
    "examples/tf-moz-deepspeech",
]

[profile.release]
lto = true

[profile.bench]
debug = true
